# See https://pre-commit.com/
# Can run one at a time, i.e. pre-commit run end-of-file-fixer --all
repos:
- hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
- hooks:
  - id: helmlint
  repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
- hooks:
  - id: helm-docs
  repo: https://github.com/norwoodj/helm-docs
  rev: v1.7.0
