# Issues
# 1) Could not use '.Capabilities.APIVersions.Has "autoscaling/v2"' to conditionally use 'apiVersion: autoscaling/v2'
#       Will work fine and create a v2 resource but getting an issue with ArgoCD comparison if we create this api versioned resource
#               ComparisonError unsupported HPA GVK: autoscaling/v2, Kind=HorizontalPodAutoscaler
#       So lets stick with v2beta2 for now, have left some logic as a breadcrump, but used a non existent k8s version so will be false for now
#       Speculating this is because the ArgoCD client-go version needs to catch up
#
# 2) Needed to keep order of the metrics as - memory and cpu - k8s HPA controller re-orders so lots of systems including ArgoCD have issues with this
#       See https://github.com/cortexproject/cortex-helm-chart/issues/284
#       So lets keep that order as others have done in their charts

{{- if .Values.webhook.hpa.enabled }}
{{- if and (semverCompare ">=1.25" .Capabilities.KubeVersion.Version) (.Capabilities.APIVersions.Has "autoscaling/v2") -}}      # See issue 1 above
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook
spec:
  maxReplicas: {{ .Values.webhook.hpa.maxReplicas }}
  metrics:                                                      # See issue 2 above
  {{- if .Values.webhook.hpa.targetMemoryUtilizationPercentage }}
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.webhook.hpa.targetMemoryUtilizationPercentage }}
        type: Utilization
    type: Resource
  {{- end }}
  {{- if .Values.webhook.hpa.targetCPUUtilizationPercentage }}
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.webhook.hpa.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
  {{- end }}
  minReplicas: {{ .Values.webhook.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-identity-webhook
{{- end }}




# PENDING: Remove me
---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook-capabilities
data:
  caps: |
    {{- toYaml .Capabilities | nindent 4 -}}
 ata:
  capsAuto: |
    autocaling/v2: {{ .Capabilities.APIVersions.Has "autoscaling/v2" }}
