apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: metrics
    port: 9999
    targetPort: 9999
  selector:
    app.kubernetes.io/name: pod-identity-webhook
