apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: webhook-admission
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook
webhooks:
- admissionReviewVersions: {{ toYaml .Values.webhookAdmission.reviewVersions | nindent 2 }}
  clientConfig:
    service:
      name: pod-identity-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate
      port: 443
  failurePolicy: {{ .Values.webhookAdmission.failurePolicy }}
  matchPolicy: Equivalent
  name: pod-identity-webhook.amazonaws.com
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
