apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: webhook-admission
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-identity-webhook-admission
subjects:
- kind: ServiceAccount
  name: pod-identity-webhook-admission
  namespace: {{ .Release.Namespace }}
