# Image's logic gets all secrets in the namespace, since we need to create a secret we cannot restirct with a resourceName
# Tried with a resource name, but kubectl auth can-i create secrets/pod-identity-webhook --as=system:serviceaccount:default:pod-identity-webhook-admission
# indicates this would not work, guess it is a POST to /secrets rather than a PUT /secrets/xyz
#
# Can also use this to see privs:  kubectl auth can-i --list --as=system:serviceaccount:default:pod-identity-webhook-admission
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: webhook-admission
    app.kubernetes.io/name: pod-identity-webhook
  name: pod-identity-webhook-admission
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
