{
 "title": "IRSA/pod-identity-webhook",
 "description": "Dashboard for the AWS IRSA pod-identity-webhook",
 "tags": [
  "irsa",
  "pod-identity-webhook"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"apiserver\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"pod-identity-webhook\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "SA cache polulated",
   "type": "stat",
   "description": "Indicates if the pod-identity-webhook has been used - SA cache populated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(pod_identity_webhook_used{instance=~\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Requests (count)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_count{instance=~\"$instance\"}[5m])) by (verb, path, code)",
     "legendFormat": "{{verb}}-{{path}}-{{code}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_latencies_bucket{instance=~\"$instance\"}[5m])) by (instance, verb, path)",
     "legendFormat": "{{instance}}-{{verb}}-{{path}}"
    }
   ]
  }
 ]
}